### ISSUE TITLE
Start using InversifyJS

### ISSUE THREAD

**Issue by gep13** [gep13/CI-CD-assets-vscode#40]
As per this blog post:

https://rpeshkov.net/blog/vscode-extension-di/

As suggested by @admiringworm

**Comment by AdmiringWorm** [comment]
Just a thought, this could also open up the possibility to have dynamic commands (through a quick pick list, at least until https://github.com/Microsoft/vscode/issues/1422 is implemented) as well.

**Comment by AdmiringWorm** [comment]
Scratch that, the possibility already exists.
